# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.loader.grub = {
    enable = false;
    efiSupport = true;
    copyKernels = true;
    zfsSupport = true;
    mirroredBoots = [
      { 
        devices = [ "nodev" ]; 
        path = "/boot1"; 
      }
      { 
        devices = [ "nodev" ]; 
        path = "/boot2"; 
      }
    ];
  };

  boot.loader.systemd-boot = {
    enable = true;
  };

  boot.loader.efi = {
    canTouchEfiVariables = true;
  };

  boot.kernelParams = [ "libata.force=noncq" ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/ROOT/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/var/lib/docker" = {
    device = "rpool/data/docker";
    fsType = "zfs";
  };

  fileSystems."/var/nas" =
    { device = "rpool/nas";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FA8A-2D3D";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # High-DPI console
  console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
